import React, { useEffect, useState } from 'react'
import main from "../../styles/Layout.module.css"
import { useRouter } from 'next/router';
import {useListings} from "../../controllers/useListings"
import ListingCard from '../../components/ListingCard';
import styles from "../../styles/pages/Home.module.css"
import Head from 'next/head';
import CategoryBar from '../../components/CategoryBar';
import { getCategories } from '../../controllers/getCategories';

function Category() {
    const router = useRouter();
    const {category} = router.query
    const {listings, isLoading} = useListings();
    const [filteredList, setFilteredList] = useState([]);
    const categories = getCategories();
    const title = "Category | " + category;
    
    useEffect(()=>{
      let array = [];
      const filterList = () => {
        listings.forEach(listing => {
          if (listing.category.includes(category)){
            array.push(listing);
          }
        }
        ) 
        setFilteredList(array);
      }
      filterList();
        
    },[listings, category])


  return (
    <div className={main.container}>

      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.wrapper}>
        <CategoryBar categories={categories} />

        
        <div className={styles.listings}>
          {filteredList.map(listing => (
              <ListingCard listing={listing} key={listing.id}/>
          ))}
        </div>

      </div>
    </div>
  )
}

export default Category