import Head from "next/head";
import styles from "../styles/pages/Home.module.css";
import { useListings } from "../controllers/useListings";
import { getCategories } from "../controllers/getCategories";
import CategoryBar from "../components/CategoryBar";
import ListingCard from "../components/ListingCard";
import Link from "next/link";
import Loader from "../components/Loader";



export default function Home(props) {
  const listings = props.pageProps.data.listings;
  //const {listings, isLoading} = useListings();

  return (
    <div className={styles.container}>
      <Head>
        <title>Listings App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.wrapper}>
        <CategoryBar />        
        <div className={styles.listings}>
          {listings.map(listing => (
              <ListingCard listing={listing} key={listing.id}/>
          ))}
        </div>

      </div>

    </div>
  );
}

export async function getServerSideProps(){
  const res = await fetch(process.env.LOCAL_URL + "/api/fetchListings");
  const data = await res.json();
  return {
      props: { data }
  }
}